config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :session
  resources :users

  resources :subs
  resources :posts

  resources :comments


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

    validates :content, :user, presence: true

    belongs_to(:user)
    belongs_to(:post)
end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: true
  belongs_to(:user)
  belongs_to(:sub)

  has_many(:comments,
  primary_key: :id,
  foreign_key: :post_id,
  class_name: "Comment"
  )
end

app/models/sub.rb
class Sub < ApplicationRecord

  validates :title, :description, presence: true

  belongs_to :moderator,
  primary_key: :id,
  foreign_key: :moderator_id,
  class_name: :User

  has_many(:posts,
  primary_key: :id,
  foreign_key: :sub_id,
  class_name: "Post"
  )

end

app/models/user.rb
class User < ApplicationRecord

  validates :username, :password_digest, presence: true
  validates :session_token, :username, uniqueness: true

  has_many :subs,
  primary_key: :id,
  foreign_key: :moderator_id,
  class_name: :Sub

  has_many(:posts,
  primary_key: :id,
  foreign_key: :user_id,
  class_name: "Post"
  )

  has_many(:comments,
  primary_key: :id,
  foreign_key: :user_id,
  class_name: "Comment"
  )

  attr_reader :password

  validates :password, length: {minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil if user.nil?
    return user if user.is_password?(password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    # @current_user ||= User.find_by(session_token: session[:session_token])
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login!(user)
    @current_user = user
    session[:session_token] = @current_user.reset_session_token!
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def require_logged_out
    redirect_to new_session_url if logged_in?
  end

  helper_method :current_user, :logged_in?


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_logged_in

    def create
      @comment = Comment.new(comment_params)
      @comment.user_id = current_user.id
      if @comment.save
        redirect_to post_url(@comment.post_id)
      else
        flash[:errors] = @comment.errors.full_messages
        render :new
      end
    end

    def destroy
      @comment = Comment.find(params[:id])
      @comment.destroy
      redirect_to post_url(@comment.post_id) 
    end

    def comment_params
      params.require(:comment).permit(:content, :user_id, :post_id)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_logged_in

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_url(@post) #show page
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end


  def update
    @post = current_user.posts.find(params[:id])
    # @post.sub_id = params[:sub_id]
    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash[:errors] = ['You are not the owner of this Post']
      # render :edit
      redirect_to post_url(@post)
    end
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to subs_url # look at this later
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, :user_id, :sub_id, sub_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :require_logged_in, only: [:destroy]
  before_action :require_logged_out, only: [:new, :create]

  def new
    render :new
  end

  def create
    @user  = User.find_by_credentials(params[:user][:username],params[:user][:password])
    # @user = User.find_by_user(session_params)
    if @user
      login!(@user)
      redirect_to subs_url
    else
      flash[:errors] = ["INvalid sign in credentials"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end


  # def session_params
  #   params.require(:user).permit(:username, :password)
  # end



end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_logged_in
  helper_method :index
  def new
    @sub = Sub.new
    render :new
  end

  def create #moderators
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
    render :index
  end

  def update
    @sub = current_user.subs.find(params[:id])
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy
    redirect_to subs_url
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


def new
  render :new
end

def create
  @user = User.new(user_params)
  # debugger
  if @user.save
    login!(@user)
    redirect_to subs_url
  else
    flash[:errors] = @user.errors.full_messages
    render :new
  end
end

def user_params
  params.require(:user).permit(:username, :password)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Redditclone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

    <% if logged_in? %>
    <%= current_user.username %>
    <%= button_to "Sign Out", session_url, method: :delete %>
    <% else %>
    <%= link_to "Sign In", new_session_url %>
    <%= link_to "Sign Up", new_user_url %>
    <% end %>

  <body>
    <img src="https://vetstreet.brightspotcdn.com/dims4/default/c2616f9/2147483647/thumbnail/645x380/quality/90/?url=https%3A%2F%2Fvetstreet-brightspot.s3.amazonaws.com%2F99%2F415260a80611e0a0d50050568d634f%2Ffile%2FSiberian-Husky-3-645mk062811.jpg" alt="Mountain View" style="width:304px;height:228px;">

    <img src="http://wallpapercave.com/wp/LmOgKXz.jpg" alt="Mountain View" style="width:304px;height:228px;">
    <%= yield %>
    <img src="http://cdn1-www.dogtime.com/assets/uploads/gallery/siberian-husky-dog-breed-pictures/siberian-husky-dog-breed-pictures-3.jpg" alt="Mountain View" style="width:304px;height:228px;">

      <img src="http://cdn1-www.dogtime.com/assets/uploads/gallery/siberian-husky-dog-breed-pictures/siberian-husky-dog-breed-pictures-2.jpg" alt="Mountain View" style="width:304px;height:228px;">
      <br>
      <br>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post!!</h1>
<form class="" action="<%= post_url(@post) %>" method="post">

<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <input type="hidden" name="_method" value="patch">

  <label>Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <label>URL
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>

  <label>Content
    <input type="text" name="post[content]" value="<%= @post.content %>">
  </label>

  <input type="submit" name="" value="Submit Edited Post">

</form>

app/views/posts/new.html.erb
<h1>Create New Post!!</h1>
<form class="" action="<%= posts_url%>" method="post">

<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
    <input type="text" name="post[title]" value="">
  </label>

  <label>URL
    <input type="text" name="post[url]" value="">
  </label>

  <label>Content
    <input type="text" name="post[content]" value="">
  </label>

  <select name="post[sub_id]" >
    <% Sub.all.each do |sub| %>
    <option value="<%= sub.id %>"><%= sub.title %></option>
    <% end %>
  </select>
  <input type="submit" name="" value="Submit Post">

<input type="text" name="" value="">
  <br>
  <br>
  <%= link_to "BACK", subs_url %>
</form>

app/views/posts/show.html.erb
BY <h3>  <%= @post.user.username %>  </h3>
<br>
          <%= @post.title %>
          <br>
          <br>
        <a href="<%= @post.url %>">Portal to <%= @post.title %></a>
        <br>
          <br>
          <%= @post.content %>
          <br>
          <br>
          <%= button_to  "Back to " + @post.sub.title, sub_url(@post.sub_id), method: :get %>

          <br>
          <br>
          <%= link_to "Edit Post", edit_post_url %>
            <h3>Comments:</h3>
            <br>
          <% @post.comments.each do  |comment| %>
          <%= (comment.user.username).capitalize %> said:
          <br>
          <%=  comment.content %>
          <%= button_to "Upvote (I like this shit)", post_url(@post), method: :get  %>
          <%= button_to "Downvote (I hate this shit)", post_url(@post), method: :get  %>
          <%= button_to "Remove Comment", comment_url(comment), method: :delete %>
          <br>
          <br>
          <% end %>
          <h3>Add Comment</h3>
          <form class="" action="<%= comments_url %>" method="post">
        <input type="hidden" name="comment[post_id]" value="<%= @post.id %>">

        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <label>Content
            <input type="text" name="comment[content]" value="">
          </label>
          <input type="submit" name="" value="Add Comment">
          </form>

app/views/subs/edit.html.erb
<h1>Edit Subform</h1>
<form class="" action="<%= sub_url(@sub) %>" method="post">

<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="hidden" name="_method" value="patch">

  <label>Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label>Description
  <textarea rows="8" cols="40" name="sub[description]"><%= (@sub.description).capitalize %>
  </textarea>
</label>





  <input type="submit" name="" value="Edit DIS">

</form>

app/views/subs/index.html.erb
<h3>ALL THE SUB FORUMS!</h3>


<% @subs.each do |sub| %>
<%= link_to (sub.title).capitalize, sub_url(sub) %>
 <br>
 <br>
<% end %>

<%= button_to "Add Subs", new_sub_url, method: :get %>

app/views/subs/new.html.erb
<h1>Create New Subform</h1>
<form class="" action="<%= subs_url %>" method="post">

<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label>Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>

  <input type="submit" name="" value="Create DIS">

</form>

app/views/subs/show.html.erb
<h2> <%= @sub.title %> </h2>


<br>
Subforum Description:
<br>
<br>
<%= (@sub.description).capitalize %>
<br>
<br>

  <% @sub.posts.each do |post| %>
  <%= link_to post.title, post_url(post) %>
    <br>
  <% end %>


<br>
<br>
<%= button_to "Back to SubForum", subs_url, method: :get %>
<br>
<%= button_to "Edit Sub", edit_sub_url, method: :get %>
<br>
<br>
  <%= link_to "Add Post", new_post_url %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<form class="" action="<%= users_url %>" method="post">

<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Username
    <input type="text" name="user[username]" value="">
  </label>

  <label>Password
    <input type="text" name="user[password]" value="">
  </label>

  <input type="submit" name="" value="GET UP IN DIS">

</form>